### PR TITLE
Update from upstream

### PR DESCRIPTION
**Pull request by bagedevimo**

### CODE REVIEW

**Comment by akampjes** [comment]
Let me know if I'm wrong but all that's happening in this merge is that we don't update the ruby version to 2.3 instead using our own version and we also maintain a google and LDAP auth version of the setup script.

Is that all?

If so, LGTM :+1:

**Comment by kuahyeow** [comment]
And beetil too ? :)

**Comment by akampjes** [comment]
I don't remember seeing beetil mentioned in it. Our merge didn't touch our beetil integration code?

**Comment by bagedevimo** [comment]
This merge doesn't cover Thong's beetil code. 

That's all this should be. Thanks Andrew. Merging!

**Pull request merged**
